### ISSUE TITLE
issue when start the bot

### ISSUE THREAD

**Issue by Erreur32** [chaun14/chaunBot#10]
Salut ce bot m'a l'air sympa !!
 j'ai tenté de l'installer , il se lance bien , rempli la DB sql mais après il me met une erreur:

```

_________ .__                       __________        __
\_   ___ \|  |__ _____   __ __  ____\______   \ _____/  |_
/    \  \/|  |  \\__  \ |  |  \/    \|    |  _//  _ \   __\
\     \___|   Y  \/ __ \|  |  /   |  \    |   (  <_> )  |
 \______  /___|  (____  /____/|___|  /______  /\____/|__|
        \/     \/     \/           \/       \/

/home/bot/Discord/chaunBot/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read properties of undefined (reading 'statsSave')
    at /home/bot/Discord/chaunBot/events/ready.js:109:24
    at Query.<anonymous> (/home/bot/Discord/chaunBot/modules/sql.js:78:9)
    at Query.<anonymous> (/home/bot/Discord/chaunBot/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/bot/Discord/chaunBot/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/bot/Discord/chaunBot/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/home/bot/Discord/chaunBot/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
    at Query.EofPacket (/home/bot/Discord/chaunBot/node_modules/mysql/lib/protocol/sequences/Query.js:133:8)
    at Protocol._parsePacket (/home/bot/Discord/chaunBot/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/bot/Discord/chaunBot/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/bot/Discord/chaunBot/node_modules/mysql/lib/protocol/Parser.js:43:10)

```

Je vois le bot se co sur discord sans souci :
![image](https://user-images.githubusercontent.com/2248137/165097613-aad12c9b-64e5-4ef1-a6fb-715ff11bdf3e.png)

_Version installed_ :  

**node -v**
v16.14.2 ( maybe related ?? )
**mysql -v**
10.5.15-MariaDB-0+deb11u1 Debian 11

Est-ce des version trop a jour ?
Je loupe un truc a faire ?

Merci

**Comment by chaun14** [comment]
Bonjour il suffit d'initialiser la base de donnée en créant une ligne dans la table botSettings avec comme bot_id l'id du bot et dans statsSave un array vide `[]`

**Comment by Erreur32** [comment]
Merci pour le feedback ;)

OK  J'ai créée une nouvelle entrée  !

Mais la  je lutte avec une erreur au démarrage (Alors que ça marchait bien tout à l'heure :s)  

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'express'
```

J'ai bien sur tenté de refaire un 

```
npm install
npm install -g express
npm install express
npm install --save express
```

    Aurais-tu une idée pour fixer le problème ? je sèche...

**Comment by chaun14** [comment]
Vérifie que les modules se sont installés correctement, tu as du les supprimer dans la manip

**Comment by Erreur32** [comment]
Yes ca marche now !
